### ISSUE TITLE
[testnet] ERR Stopping peer for error

### ISSUE THREAD

**Issue by 99Kies** [cosmos/testnets#325]
I'm trying to run the verifier node of the test network, but I'm having problems synchronizing the data.

I encountered the following error when I started the service with `v7.0.2` version.
```
9:11AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
9:11AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"3e506472683ceb7ed75c1578d092c79785c27857","ip":"165.232.159.99","port":26656}
9:11AM INF Reconnecting to peer addr={"id":"3e506472683ceb7ed75c1578d092c79785c27857","ip":"165.232.159.99","port":26656} module=p2p
9:11AM INF Dialing peer address={"id":"3e506472683ceb7ed75c1578d092c79785c27857","ip":"165.232.159.99","port":26656} module=p2p
9:11AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
9:11AM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
9:11AM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
9:11AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"639d50339d7045436c756a042906b9a69970913f","ip":"165.232.138.225","port":26656}
9:11AM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"639d50339d7045436c756a042906b9a69970913f","ip":"165.232.138.225","port":26656}
9:11AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
```

this is my config:
```toml
[statesync]
# State sync rapidly bootstraps a new node by discovering, fetching, and restoring a state machine
# snapshot from peers instead of fetching and replaying historical blocks. Requires some peers in
# the network to take and serve state machine snapshots. State sync is not attempted if the node
# has any local state (LastBlockHeight > 0). The node will have a truncated block history,
# starting from the height of the snapshot.
enable = true

# RPC servers (comma-separated) for light client verification of the synced state machine and
# retrieval of state data for node bootstrapping. Also needs a trusted height and corresponding
# header hash obtained from a trusted source, and a period during which validators can be trusted.
#
# For Cosmos SDK-based chains, trust_period should usually be about 2/3 of the unbonding time (~2
# weeks) during which they can be financially punished (slashed) for misbehavior.
rpc_servers = "rpc.sentry-01.theta-testnet.polypore.xyz:26657,rpc.sentry-02.theta-testnet.polypore.xyz:26657"
trust_height = 13515478
trust_hash = "E694714C5AB4A4899D6C787FA6061E65EBACA80A70894AF6A1F2D8D46258567E"
trust_period = "168h0m0s"
```

and this is my start command: 
```
gaiad start --x-crisis-skip-assert-invariants
```

----

By the way can you help me judge my understanding --- my understanding is that I need to run the node with `v6.0.0` first, wait for the sync to reach block `9283650`, then shut down the current sync service, switch the version to `v7.0.0-rc0` and then restart the service again.
